stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile.cloud-agent
      buildContext: .
      tag: weave-scope
      registry: 127.0.0.1:34078
timeout: 60
notification: {}
