stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: /docker/Dockerfile.scope
      buildContext: .
      tag: weave scope
      registry: 127.0.0.1:34356
timeout: 60
notification: {}
